if node['platform_family'] == 'debian'
  default['apache_dir'] = '/etc/apache2'
  default['apache_package'] = 'apache2'
  default['apache_service'] = 'apache2'
  default['apache_vhost_conf_dir'] = '/etc/apache2/sites-enabled'
  default['apache_log_dir'] = '/var/log/apache2'
elsif node['platform_family'] == 'rhel'
  default['apache_dir'] = '/etc/httpd'
  default['apache_package'] = 'httpd'
  default['apache_service'] = 'httpd'
  default['apache_ssl_module_package'] = 'mod_ssl'
  default['apache_vhost_conf_dir'] = '/etc/httpd/conf.d'
  default['apache_log_dir'] = '/var/log/httpd'
end
